<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Google Drive Example App</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    </head>
    <body>
    <?php 
        include_once('dbConfig/connection.php');
        $q="select * from uploads where file_id is null";
        $result=$database->query($q);
        $i=0;
        ?>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12  " style="overflow-x: auto;">

            <table class="table table-striped ">
  <thead>
    <tr>
      <th scope="col">S.No</th>
      <th scope="col">File Name</th>
      <th scope="col">Faculty</th>
      <th scope="col">Course</th>
      <th scope="col">Branch</th>
      <th scope="col">Semester</th>
      <th scope="col">Uploaded By</th>
      <th scope="col">Uploaded on</th>
      <th scope="col">file size(kb)</th>
      <th scope="col">View</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  <?php
    if(count($files)==0)
    {
        ?>
        <tr>
            <td colspan="11">no records to display</td>
        </tr>
        <?php
    }
    else
    {
        while($row=$result->fetch_assoc())
    {

        foreach($files as $file_name)
        {
            if(file_exists('files/'.$row['file_name']))
            {
        ?>
        <tr>
            <th scope="row"><?php echo ++$i; ?></th>
            <td><?php echo $row['file_name']; ?></td>
            <td><?php echo $row['faculty']; ?></td>
            <td><?php echo $row['course']; ?></td>
            <td><?php echo $row['branch']; ?></td>
            <td><?php echo $row['semester']; ?></td>
            <td><?php echo $row['uploaded_by_email']; ?></td>
            <td><?php echo $row['uploaded_on']; ?></td>
            <td><?php echo $row['file_size']; ?></td>
            <td>
            <a href=<?php echo "files/".str_replace(' ', '%20', $row['file_name']);  ?> target="_blank">view</a>
            </td>
            <td>
            <a href="delete.php?del=<?php echo 'files/'.$row['file_name']  ?>&id=<?php echo $row['id']  ?>">delete</a>
            </td>
        </tr>
        <?php   
        break;   
            }
        }
    }
    }
  ?>
  </tbody>
</table>
</div>
            </div>
        </div>       
       
        <form id="myform" method="post" action="list_files/upload.php">
            <input type="submit" value="send" name="submit" id="clickButton">
        </form>


        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    </body>
</html>
